### ISSUE TITLE
More fields in ranking contract

### ISSUE THREAD

**Issue by schmidsi** [melonproject/smart-contracts#354]
We display 4 fields in the frontend:
- Name
- Shareprice
- Inception (or creation date)
- Address (for deep links)

Now the contract returns only address and shareprice so we need to make 2 extra calls to get all data we need:
- Fund.getName
- Fund.getCreationTime

Can you just return these information also from the ranking contract?

**Comment by retotrinkler** [comment]
FundRanking looks right except https://github.com/melonproject/protocol/blob/v0.6.2-deploy.9/src/FundRanking.sol#L1 should be `pragma solidity ^0.4.19;`

**Comment by travs** [comment]
Fixed by #378 and earlier commits (will close when merged)

**Comment by retotrinkler** [comment]
@schmidsi or @jennazenk is this still relevant in context of ranking.melon.fund service?

**Comment by ferranbt** [comment]
We have been using ranking.melon.fund because it was too expensive to get all the data (including name and creation time) in terms of RPC calls as pointed by @schmidsi. If this is fixed on the protocol level we just can get rid of ranking.melon.fund.

**Comment by retotrinkler** [comment]
think for this we need to change `name` from `string` to `bytes32` which is possible but has two down-sides

- limits name length to 32 bytes
- increases contract size when conversion needs to be applied from `string` to `bytes32` can be found here https://github.com/melonproject/protocol/pull/378

think easiest is to default to `bytes32`

**Comment by schmidsi** [comment]
32 bytes should be sufficient. It's a name, not a strategy description ;)
