### ISSUE TITLE
Unhandled Division by Zero in Pricefeed getInvertedPrice

### ISSUE THREAD

**Issue by travs** [melonproject/smart-contracts#392]
## Impact
getInvertedPrice will throw if an asset price is set to 0, leading to a denial of service
condition when requesting the inverted price for that asset.

## Details
In the function getInvertedPrice, the price of an asset is retrieved via getPrice and the
result is stored in the inputPrice variable. The issue arises on line 193 of Pricefeed.sol, where
a division by zero may be performed if an asset price is set to zero by the Pricefeed owner.

## Recommendation
Account for the possibility of inputPrice equaling 0 in getInvertedPrice, and gracefully
handle this scenario.

**Comment by travs** [comment]
Can we handle this by updating other assets, but not the one set to zero?

**Comment by retotrinkler** [comment]
> Can we handle this by updating other assets, but not the one set to zero?

what do u mean by this?

> Maybe also the problem diminishes when we use the canonical pricefeed.

agree

**Comment by retotrinkler** [comment]
To give some context to this, its `getInvertedPrice` is only used once in `executeRequest` it does not affect `redeemAllOwnedAssets` or `emergencyRedeem`.

Its one of our security assumptions that the price feed is operated correctly.

@travs yeah think `revert()` would make sense implemented it here https://github.com/melonproject/protocol/tree/pricefeeddivisionthroughzero for next release

**Comment by travs** [comment]
> what do u mean by this?

Meant that we could update the assets that had non-zero prices, but I agree with the `revert` approach since we assume correct operation.

**Comment by travs** [comment]
Switched to CanonicalPriceFeed which does not allow zero prices now
