### ISSUE TITLE
AssetRegistrar should return all the assets

### ISSUE THREAD

**Issue by ferranbt** [melonproject/smart-contracts#407]
Previous version of DataFeed had a function 'getRegisteredAssetAt' which could be used to get all the assets available. As noted by @travs, the only way now to access the assets is through the fund. I think that in this way, DataFeed just loses flexibility. semantically, you have to be able to get data from the feed independently from the fund. Applications like charts for price feed prices would be impossible to build now.

**Comment by retotrinkler** [comment]
reason for this was because of the solidity constraints we have. to do above we would need an array on solidity execution of larger arrays can lead to a function failing

should be possible now however w dynamic size of arrays we can return for read calls
