### ISSUE TITLE
Update PriceUpdated event to provide a hash of the new prices instead of a timestamp

### ISSUE THREAD

**Issue by schmidsi** [melonproject/smart-contracts#433]
# Summary
Replace 
```
event PriceUpdated(uint timestamp);
```

with

```
event PriceUpdated(bytes64 hash);
```

In: https://github.com/melonproject/smart-contracts/blob/v0.7.2-alpha.1/src/pricefeeds/PriceFeedInterface.sol#L11 and implementing contracts.

Where `hash` is a hash over all updated prices. Something like `hash([0xAddressOfBaseAsset/0xAddressOfQuoteAsset:price, ...])`.

# Background
If one wants to look up historical prices he needs to do the following:

- Search for past `PriceUpdated` events
- Get the block number of the event
- Query the blockchain for `PriceFeed.getPrices(...)` at the specific block number to get the historic prices.

But this supposedly only works with `parity --pruning=archive`. I did not actually test this, but it was not possible to lookup prices older than 1000 blocks.

# Proposed solution

The best possibility to store and receive historical prices would be:
- The price feed operator not only stores the current price on the blockchain, it also sends them to a database (orbit-db on IPFS or a centralised solution). But it stores a hash over all prices in this event.
- A client can retrieve historic price information from an untrusted source and check its validity by verifying the hash from the blockchain.

Having `timestamp` as an argument does not make any sense since every event is bound to a block which is already timestamped.

**Comment by ferranbt** [comment]
I think this comes back also to #432. The objective of the events is either be used as a way to detect when something happened in real time or to be used as a historic feed to query data. We have to decided which is the use case of the events.

**Comment by travs** [comment]
Spoke about this in the sync; we can add this in the next release
