### ISSUE TITLE
Competition contract changes + deployment

### ISSUE THREAD

**Issue by jennazenk** [melonproject/smart-contracts#444]
- [ ] Hash of T&Cs to include in competition contract : QmXuUfPi6xeYfuMwpVAughm7GjGUjkbEojhNR8DJqVBBxc
(see on ipfs https://ipfs.io/ipfs/QmXuUfPi6xeYfuMwpVAughm7GjGUjkbEojhNR8DJqVBBxc) 

- [ ] Rate MLN/ETH needs to be adjusted from 22 to 20 MLN/ETH

- [ ] At deployment, could you pls automatically whitelist the following address: 0xa80b5f4103c8d027b2ba88be9ed9bb009bf3d46f

**Comment by travs** [comment]
Fixed by #446
