### ISSUE TITLE
Deployment configuration

### ISSUE THREAD

**Issue by jennazenk** [melonproject/smart-contracts#445]
As discussed previously with @travs and @GauthamN , for next deployment, could we have the 3 following configurations : 

- kovan (regular kovan, OnlyManager compliance)
- kovan-competition (reproduces competition conditions, with OnlyCompetition compliance)
- live (competition conditions on main net, with OnlyCompetition compliance)

**Comment by GauthamN** [comment]
kovan - NoComplianceCompetition.sol
kovan-competition: OnlyCompetition.sol
live: OnlyCompetition.sol

**Comment by travs** [comment]
This one is done, it's just that `OnlyCompetition.sol` is called `CompetitionCompliance.sol`.
@GauthamN please re-open this if that's incorrect
