### ISSUE TITLE
CanonicalPriceFeed does not prevent price manipulation

### ISSUE THREAD

**Issue by jennazenk** [melonproject/smart-contracts#459]
## Details 
Prices from the price feed are used to enforce maximum buy-ins and, more importantly, to compute how much Melon (MLN) to invest in a contract. If a malicious actor is able to compromise the price feed, they can contribute a small amount of ether but receive a very large amount of MLN.
The price feed is based on a staking scheme. The point-in-time price is the median of the prices submitted by the top  n  stakers. The  burnStake  function ostensibly allows the feed owner to punish bad actors, but nothing prevents a malicious participant from removing their stake before it can be burned. An attack can be performed in a single transaction, in which an attacker:
1. becomes all top  n  stakers (from different contracts),
2. submits a malicious price from those contracts,
3. registers for the competition (making use of that price), 4. and finally withdraws the stakes.
Additionally, an attacker could front-run transactions attempting to burn their stake.

## Recommendation 
Any funds staked to participate in the price feed should be held for long enough that they can be later slashed as punishment. Stakers should not be able to withdraw their stake immediately, instead a significant delay should be added between unstaking and stakers being able to withdraw their stake.

**1st response:**
We added a delay in the staking contract.
**Solidified response:**
Unfortunately the attempted fix does not properly address the issue. Melonport added a delay that prevents users from unstaking X amount of time after last staking. An attacker can wait an X + 1 amount of time, after initially staking and then perform the attack described above. What is needed is a withdraw delay after the last time they  influenced the price : so Melonport has sufficient time to realize a price manipulation has been attempted and burn the attacker’s stake, before the attacker can remove their funds from danger. In other words the unstake action (the act of removing your influence from the price feed), should be distinct from withdrawal (the act of revoking custody from the stake bank and transferring the assets back to the staker). The delay needs to exist between these two actions without regard to when the user began staking.

**Comment by GauthamN** [comment]
Isn't this done @travs
