### ISSUE TITLE
 Incorrect initialisation of highWaterMark

### ISSUE THREAD

**Issue by jennazenk** [melonproject/smart-contracts#470]
## Details

In the  `Fund` contract constructor highWaterMark is initialised to  `10 ** getDecimals()`. Our reading of the code is that this should be initialised to 0.

## Recommendation
Replace Fund.sol, Line 163
`highWaterMark: 10 ** getDecimals(),`

with: 
`highWaterMark: 0,`

**Comment by GauthamN** [comment]
I believe since Fund starts out at the sharePrice of of 10 ** getDecimals(), the initialisation is valid.

**Comment by travs** [comment]
I agree with Gautham here; though maybe we can change the initial share price to get the price dynamically, in case we change the initial shareprice some time. In other words get it from `calcSharePrice()` directly

**Comment by jennazenk** [comment]
agreed - not sure if we should get it from `calcSharePrice` (if pricefeed is down, it would be 0 and might cause issue for first investment request?)

**Comment by travs** [comment]
@jennazenk yeah good point. Leaving it as-is
